### list pedidos
GET http://localhost:3000/pedidos

### get pedido
GET http://localhost:3000/pedidos/1

### create pedidos
POST http://localhost:3000/pedidos
Content-Type: application/json

{
    "client": "Everton",
    "items": [1],
    "total": 12,
    "status": "Pendente"
}

### update pedidos
PATCH http://localhost:3000/pedidos/1
Content-Type: application/json

{
    "client": "Gerson"
}

### delete pedidos
DELETE http://localhost:3000/pedidos/1